name: BestCF

on:
  schedule:
    - cron: '24 */3 * * *'
  workflow_dispatch:

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: BestCF
      run: |
        python .github/workflows/bestcf.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
    - name: Clean up Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ github.token }}
         
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 3
