name: 'cc'

on:
  schedule:
    - cron: '38 23 */2 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Clean up Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ github.token }}
         
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
