name: Update cm

on:
  schedule:
    - cron: '37 */12 * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发
  #push: # 允许提交触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4      

        
    - name: Run script
      run: python ${{ github.workspace }}/cm.py
    - name: Make script executable and install dependencies
      run: |
          set -e
          chmod +x CloudflareST
          pip install pandas

    - name: 测速
      run: |
          set -e
          ./CloudflareST -t 8 -sl 5 -n 100 -dn 15 -dt 4 -tp 8443 -tlr 0 -o HKG.csv
       
          rm -f ip.txt
    - name: Commit changes
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -n "$(git status --porcelain)" ]; then
            git add HKG.csv
            git commit -m "Automatic update"
            git push --force origin main
          else
           echo "No changes detected, skipping commit."
          fi
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
