name: fand

on:
  schedule:
    - cron: "8 2-23/1 * * *"
  workflow_dispatch:

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

 #   - name: Set up Python
   #   uses: actions/setup-python@v4
   #   with:
    #    python-version: 3.8

   # - name: Install Dependencies
   #   run: |
   #     python -m pip install --upgrade pip
   #     pip install requests

    - name: BestCF
      run: |
        python .github/workflows/fand.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
